/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Tampilan;

import com.formdev.flatlaf.themes.FlatMacLightLaf;
import javax.swing.UIManager;
import java.sql.SQLException;
import Kelas.User;

/**
 *
 * @author M. Aziz Ridwan
 */
public class FrameUser extends javax.swing.JFrame {

    /**
     * Creates new form FrameUser
     */
    public FrameUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tUsername = new javax.swing.JTextField();
        tPassword = new javax.swing.JPasswordField();
        tFullname = new javax.swing.JTextField();
        cStatus = new javax.swing.JComboBox<>();
        jTambah = new javax.swing.JLabel();
        tEmail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tUsername.setBackground(new java.awt.Color(255, 102, 196));
        tUsername.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tUsername.setForeground(new java.awt.Color(255, 255, 255));
        tUsername.setBorder(null);
        getContentPane().add(tUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 180, 30));

        tPassword.setBackground(new java.awt.Color(255, 102, 196));
        tPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tPassword.setForeground(new java.awt.Color(255, 255, 255));
        tPassword.setBorder(null);
        getContentPane().add(tPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 192, 180, 30));

        tFullname.setBackground(new java.awt.Color(255, 102, 196));
        tFullname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tFullname.setForeground(new java.awt.Color(255, 255, 255));
        tFullname.setBorder(null);
        getContentPane().add(tFullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 242, 180, 30));

        cStatus.setBackground(new java.awt.Color(255, 102, 196));
        cStatus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cStatus.setForeground(new java.awt.Color(255, 255, 255));
        cStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aktif", "Tidak aktif", " " }));
        cStatus.setBorder(null);
        cStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cStatusActionPerformed(evt);
            }
        });
        getContentPane().add(cStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 170, 30));

        jTambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTambahMouseClicked(evt);
            }
        });
        getContentPane().add(jTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 356, 330, 40));

        tEmail.setBackground(new java.awt.Color(255, 102, 196));
        tEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tEmail.setForeground(new java.awt.Color(255, 255, 255));
        tEmail.setBorder(null);
        getContentPane().add(tEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 146, 180, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/frameuser.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cStatusActionPerformed

    private void jTambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTambahMouseClicked
        // TODO add your handling code here:
        try {
            User user = new User();
            user.setUser_name(tUsername.getText());
            user.setUser_email(tEmail.getText());
            user.setUser_password(tPassword.getText());
            user.setUser_fullname(tFullname.getText());
            if (cStatus.getSelectedItem().equals("Aktif")) {
                user.setUser_status(1);
            } else {
                user.setUser_status(0);
            }
            user.tambahUser();
        } catch (SQLException sQLException) {
        }
    }//GEN-LAST:event_jTambahMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(new FlatMacLightLaf());
            UIManager.put("Button.arc", 15);
            UIManager.put("TextComponent.arc", 15);
        } catch (Exception e) {
            e.printStackTrace();
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jTambah;
    private javax.swing.JTextField tEmail;
    private javax.swing.JTextField tFullname;
    private javax.swing.JPasswordField tPassword;
    private javax.swing.JTextField tUsername;
    // End of variables declaration//GEN-END:variables
}
